version: '3'
services:
    web:
        build: .
        ports:
            - '5001:80'
            - '8081:443'
        depends_on:
            - db
        command: dotnet ef database update
    db:
        image: 'microsoft/mssql-server-linux'
        ports:
            - '1433:1433'
        volumes:
            - mssql-volume:/var/opt/mssql
        environment:
            SA_PASSWORD: 'MyComplexPassword!234'
            ACCEPT_EULA: 'Y'
volumes:
    mssql-volume:
