version: '3'
services:
    local_web:
        build: .
        ports:
            - '5001:80'
        depends_on:
            - db
        volumes:
            - ./:/app    
    db:
        image: 'microsoft/mssql-server-linux'
        ports:
            - '1433:1433'
        volumes:
            - mssql-volume:/var/opt/mssql
        environment:
            SA_PASSWORD: 'MyComplexPassword!234'
            ACCEPT_EULA: 'Y'
volumes:
    mssql-volume:
